language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-24
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - cd BrickKit
  - ./gradlew build connectedCheck createPom
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: bintray
  file: "bintray.descriptor"
  user: "thusson13"
  key:
    secure: "Pc7RZQ8ARReGYdATZJZeSY7t0dXU/VlNasNaN/LAi8DwUZQ9fJljjxz5Dg9TAEGpAkJoP0xIiAdNUcx4jm40HSQZTpnCKYSbKTIllAzPoilgaRJWlwuJshpfGGICIAVhQiaZJZR3KfAmPi3spKQ+1Q1AXSg6+fiFgcZTlxqAC6T63Ftx+gVtxv1xilQTHxyAhS5sdI5J1YEwhrxKHBC7uTXfpeouV9zEDInqGpR6iC+bZXN6AOF14cea30dcrENJhBrjQ0GnPB/Jy0GqO+fy9CmOHlBPsMaH12S0q8QqUBzRkeSJfSV1o2lrLutUE+fbzF67Okrhd5TsgZw0JcH1alHOLnDx+pGakdO7lmSLdHGCs3MVSvF4o9xhekRjHwodK2zffk9gseZmWKc81ZfejUp9VrTTkzvZmTj88qGIwGsNRDOYhD+rJeaxAyjWJBVEom0MIVk+Cgw9gz9dpZ0p4pizT65ie7n6+ruqFNKsdr46PCCGL8SWC6v+nmztwJ+amTHY51SG//0mC/d/zWsEza1EOF21YHj4r0is6/eUhl+t+goiO2TGx/z+1NMBofBs1g96T01LZPnNFd8qiyT16+IX5coXqB4LPo9l1G7F0r+qRvVnqtjunvpgXMzRidCZ7dez/cE/I6jx1MxIK7lDXnl1KSjPX7NqSRDq69+EtyE="
