language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - tools

env:
  global:
    - API=24
    - TAG=default
    - ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - export EMULATOR="system-images;android-${API};${TAG};${ABI}" # Used to install/create emulator

install:
  - echo yes | sdkmanager "tools" > /dev/null
  - echo yes | sdkmanager "platforms;android-28" > /dev/null
  - echo yes | sdkmanager "extras;android;m2repository" > /dev/null
  - echo yes | sdkmanager "extras;google;m2repository" > /dev/null
  - echo yes | sdkmanager "$EMULATOR" > /dev/null # Install emulator system image
  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f --abi "$ABI" --tag "$TAG"
  - emulator -list-avds
  - cd "$ANDROID_HOME/tools" # Bug in the current emulator release
  - emulator -avd test -no-window &
  # Start adbd, wait for device connected and show android serial
  - adb wait-for-device get-serialno

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30
  - adb shell input keyevent 82 &

script:
  - cd ${TRAVIS_BUILD_DIR}/BrickKit
  - ./gradlew build connectedCheck createPom createBintrayDescriptor
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  skip_cleanup: true
  provider: bintray
  file: "BrickKit/bricks/build/bintray.descriptor"
  user: "thusson13"
  key:
    secure: "Pc7RZQ8ARReGYdATZJZeSY7t0dXU/VlNasNaN/LAi8DwUZQ9fJljjxz5Dg9TAEGpAkJoP0xIiAdNUcx4jm40HSQZTpnCKYSbKTIllAzPoilgaRJWlwuJshpfGGICIAVhQiaZJZR3KfAmPi3spKQ+1Q1AXSg6+fiFgcZTlxqAC6T63Ftx+gVtxv1xilQTHxyAhS5sdI5J1YEwhrxKHBC7uTXfpeouV9zEDInqGpR6iC+bZXN6AOF14cea30dcrENJhBrjQ0GnPB/Jy0GqO+fy9CmOHlBPsMaH12S0q8QqUBzRkeSJfSV1o2lrLutUE+fbzF67Okrhd5TsgZw0JcH1alHOLnDx+pGakdO7lmSLdHGCs3MVSvF4o9xhekRjHwodK2zffk9gseZmWKc81ZfejUp9VrTTkzvZmTj88qGIwGsNRDOYhD+rJeaxAyjWJBVEom0MIVk+Cgw9gz9dpZ0p4pizT65ie7n6+ruqFNKsdr46PCCGL8SWC6v+nmztwJ+amTHY51SG//0mC/d/zWsEza1EOF21YHj4r0is6/eUhl+t+goiO2TGx/z+1NMBofBs1g96T01LZPnNFd8qiyT16+IX5coXqB4LPo9l1G7F0r+qRvVnqtjunvpgXMzRidCZ7dez/cE/I6jx1MxIK7lDXnl1KSjPX7NqSRDq69+EtyE="
