name: CI Build
on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!master' # remove once main branch is dev
jobs:
  ci-build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        working-directory: ./BrickKit
        run: ./gradlew build
