name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    environment: publishing-environment

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11.0.1+13
          distribution: 'zulu'
          cache: gradle
      - name: Prepare environment
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      - name: Release build
        working-directory: ./BrickKit
        # assembleRelease for all modules, excluding non-library modules: sample, ui-components sample, docs
        run: ./gradlew assembleRelease
      - name: Source jar
        working-directory: ./BrickKit
        run: ./gradlew androidSourcesJar
      - name: Publish to MavenCentral
        working-directory: ./BrickKit
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseRepository
